name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Saigon
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          #language
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          #music
          plugin_music: yes
          plugin_music_provider: spotify # Use Spotify as provider
          plugin_music_mode: recent     # Set plugin mode
          plugin_music_limit: 4          # Limit to 4 entries
          plugin_music_played_at: yes    # Show timestamp (for spotify only)
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_playlist: https://open.spotify.com/embed/playlist/11Evyuckpk2S4THRnKsfIJ
          #waka
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 5                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
